language: java

notifications:
  email: false
  
before_install:
  - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar -zxf android-sdk_r22.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  - android update sdk --filter 1,4 --no-ui --force
  - android update sdk --no-ui --obsolete --force